version: '3'

services:
  postgres:
    container_name: keycloak_db
    image: "postgres:latest"
    volumes:
      - keycloak_postgresql:/var/lib/postgresql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - keycloak_network
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    volumes:
      - keycloak_data:/data
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: ${KEYCLOAK_DB}
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_SCHEMA: ${KEYCLOAK_DB_SCHEMA}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      PROXY_ADDRESS_FORWARDING: true
    ports:
      - 9000:8080
    networks:
      - keycloak_network
    depends_on:
      - postgres
volumes:
  postgres_data:
    driver: local
  keycloak_postgresql:
  keycloak_data:
networks:
  keycloak_network: